export enum EXTERNAL_ROUTES {
  WEB_APP = 'https://invest.nada.co/signup',
  DOWNLOAD = 'https://nada.onelink.me/wNEn/ksbeffng',
  TYPEFORM = 'https://form.typeform.com/to/fv2eTpuT',
  CAREERS = 'https://linkedin.com/company/hellonada/jobs',
  APPLE_STORE = 'https://apps.apple.com/us/app/nada-finance/id1615840472',
  GOOGLE_STORE = 'https://play.google.com/store/apps/details/Nada_Finance?id=com.nada.debitapp',
  HUBSPOT_MEETING = 'https://meetings.hubspot.com/deyon-robertson/accredited-investors',
  HUBSPOT_FAQS = 'https://faqs.nada.co',
}

export const UTM_PARAMETERS = [
  'utm_source',
  'utm_medium',
  'utm_campaign',
  'utm_term',
  'utm_content',
  'gclid',
  'fbclid',
  'msclkid',
  'irclickid',
  'sharedCredentialsUuid',
];

export const HEADER_LINKS = [
  { name: 'Cityfunds', link: '/' },
  { name: 'About', link: '/about' },
  { name: 'Learn', link: '/learn' },
];

export const LEGAL_LINKS = [
  { name: 'Terms of Use', link: '/terms-conditions' },
  { name: 'Privacy Policy', link: '/privacy-policy' },
  { name: 'Cookie Policy', link: '/cookie-policy' },
  {
    name: 'Rewards Program',
    link: '/rewards-program',
  },
  {
    name: 'Electronic Funds Transfer',
    link: '/electronic-funds-transfer',
  },
  {
    name: 'Consumer Complaint Policy',
    link: 'https://irgtndauzeikqqggeniu.supabase.co/storage/v1/object/public/nada/consumer-complaint.pdf',
  },
  {
    name: 'Nada SEC Filings',
    link: 'https://www.sec.gov/edgar/browse/?CIK=0001801613',
  },
  {
    name: 'Cityfunds SEC Filings',
    link: 'https://www.sec.gov/edgar/search/#/ciks=0001874979&entityName=Cityfunds%2520I%252C%2520LLC%2520(CIK%25200001874979)',
  },
];

export const FOOTER_LINKS = [
  {
    title: 'Home',
    links: [
      { name: 'Cityfunds', link: '/' },
      { name: 'Homeshares', link: '/homeshares' },
      { name: 'Accredited Investors', link: '/accredited-investors' },
      { name: 'Learn', link: '/learn' },
    ],
  },
  {
    title: 'About',
    links: [
      { name: 'About', link: '/about' },
      { name: 'Careers', link: EXTERNAL_ROUTES.CAREERS },
      { name: 'Press', link: '/press' },
      { name: 'FAQs', link: EXTERNAL_ROUTES.HUBSPOT_FAQS },
    ],
  },
  {
    title: 'Transparency',
    links: LEGAL_LINKS,
  },
];

export const SOCIAL_LINKS = [
  { name: 'Facebook', link: 'https://www.facebook.com/HelloNadaHomes' },
  { name: 'Twitter', link: 'https://twitter.com/nada_finance' },
  { name: 'Instagram', link: 'https://www.instagram.com/nadafinance' },
  { name: 'LinkedIn', link: 'https://www.linkedin.com/company/hellonada' },
  { name: 'Discord', link: 'https://discord.com/invite/AGhPSkQjYX' },
  { name: 'TikTok', link: 'https://www.tiktok.com/@nadafinance' },
];

export const FAQS = [
  {
    question: 'What is a Cityfund?',
    answer:
      "Cityfunds is the first ever index-like fund providing access to a city's home equity market. By untapping the $20T home equity space, our investments model enables our assets to appreciate 2.2x faster than the standard home appreciation.",
  },
  {
    question: 'Who are Cityfunds for?',
    answer:
      "Built for people who want to join the exponential growth of the nation's top cities.",
  },
  {
    question: 'What makes Cityfunds different?',
    answer:
      "Cityfunds is the first index-like fund providing access to a city's home equity market. Returns generated by our Homeshares product allows you to participate in home appreciation over time.",
  },
  {
    question: 'Will my money be tied up?',
    answer:
      "No! We have redemption programs in place for you. You're either thrilled about your portfolio growth or sell your shares to get your money back.",
  },
];

export enum FUND_STATUS {
  PRESALE = 'Presale',
  ACTIVE = 'Active',
  CLOSED = 'Closed',
}

export enum FUND_TYPE {
  EQUITY = 'Equity',
  DEBT = 'Debt',
}

export enum REGULATION {
  RETAIL = 'Retail',
  ACCREDITED = 'Accredited',
}

export enum LIQUIDITY {
  QUARTERLY = 'Quarterly',
  ANNUALLY = 'Annually',
}
